config/routes.rb
Rails.application.routes.draw do  get 'admin/index'
  resources 'sliders'
  resources 'services'
  resources 'structures'
  get 'inicio/index'
  root to: "inicio#index"
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:title_1, :description_1, :title_2, :description_2, :title_3, :description_3, :title_4, :description_4)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title_1 %><br>
    <%= f.text_field :title_1 %>
  </div>
  <div class="field">
    <%= f.label :description_1 %><br>
    <%= f.text_field :description_1 %>
  </div>
  <div class="field">
    <%= f.label :title_2 %><br>
    <%= f.text_field :title_2 %>
  </div>
  <div class="field">
    <%= f.label :description_2 %><br>
    <%= f.text_field :description_2 %>
  </div>
  <div class="field">
    <%= f.label :title_3 %><br>
    <%= f.text_field :title_3 %>
  </div>
  <div class="field">
    <%= f.label :description_3 %><br>
    <%= f.text_field :description_3 %>
  </div>
  <div class="field">
    <%= f.label :title_4 %><br>
    <%= f.text_field :title_4 %>
  </div>
  <div class="field">
    <%= f.label :description_4 %><br>
    <%= f.text_field :description_4 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<h1>Listing services</h1>

<table>
  <thead>
    <tr>
      <th>Title 1</th>
      <th>Description 1</th>
      <th>Title 2</th>
      <th>Description 2</th>
      <th>Title 3</th>
      <th>Description 3</th>
      <th>Title 4</th>
      <th>Description 4</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.title_1 %></td>
        <td><%= service.description_1 %></td>
        <td><%= service.title_2 %></td>
        <td><%= service.description_2 %></td>
        <td><%= service.title_3 %></td>
        <td><%= service.description_3 %></td>
        <td><%= service.title_4 %></td>
        <td><%= service.description_4 %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title 1:</strong>
  <%= @service.title_1 %>
</p>

<p>
  <strong>Description 1:</strong>
  <%= @service.description_1 %>
</p>

<p>
  <strong>Title 2:</strong>
  <%= @service.title_2 %>
</p>

<p>
  <strong>Description 2:</strong>
  <%= @service.description_2 %>
</p>

<p>
  <strong>Title 3:</strong>
  <%= @service.title_3 %>
</p>

<p>
  <strong>Description 3:</strong>
  <%= @service.description_3 %>
</p>

<p>
  <strong>Title 4:</strong>
  <%= @service.title_4 %>
</p>

<p>
  <strong>Description 4:</strong>
  <%= @service.description_4 %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>