config/routes.rb
Rails.application.routes.draw do  get 'admin/index'
  resources 'sliders'
  resources 'services'
  resources 'structures'
  get 'inicio/index'
  root to: "inicio#index"
end

app/models/slider.rb
class Slider < ActiveRecord::Base
end

app/controllers/sliders_controller.rb
class SlidersController < ApplicationController
  before_action :set_slider, only: [:show, :edit, :update, :destroy]

  # GET /sliders
  # GET /sliders.json
  def index
    @sliders = Slider.all
  end

  # GET /sliders/1
  # GET /sliders/1.json
  def show
  end

  # GET /sliders/new
  def new
    @slider = Slider.new
  end

  # GET /sliders/1/edit
  def edit
  end

  # POST /sliders
  # POST /sliders.json
  def create
    @slider = Slider.new(slider_params)

    respond_to do |format|
      if @slider.save
        format.html { redirect_to @slider, notice: 'Slider was successfully created.' }
        format.json { render :show, status: :created, location: @slider }
      else
        format.html { render :new }
        format.json { render json: @slider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sliders/1
  # PATCH/PUT /sliders/1.json
  def update
    respond_to do |format|
      if @slider.update(slider_params)
        format.html { redirect_to @slider, notice: 'Slider was successfully updated.' }
        format.json { render :show, status: :ok, location: @slider }
      else
        format.html { render :edit }
        format.json { render json: @slider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sliders/1
  # DELETE /sliders/1.json
  def destroy
    @slider.destroy
    respond_to do |format|
      format.html { redirect_to sliders_url, notice: 'Slider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slider
      @slider = Slider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slider_params
      params.require(:slider).permit(:description_1, :description_2, :description_3, :description_4, :description_5)
    end
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/views/sliders/_form.html.erb
<%= form_for(@slider) do |f| %>
  <% if @slider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slider.errors.count, "error") %> prohibited this slider from being saved:</h2>

      <ul>
      <% @slider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description_1 %><br>
    <%= f.text_field :description_1 %>
  </div>
  <div class="field">
    <%= f.label :description_2 %><br>
    <%= f.text_field :description_2 %>
  </div>
  <div class="field">
    <%= f.label :description_3 %><br>
    <%= f.text_field :description_3 %>
  </div>
  <div class="field">
    <%= f.label :description_4 %><br>
    <%= f.text_field :description_4 %>
  </div>
  <div class="field">
    <%= f.label :description_5 %><br>
    <%= f.text_field :description_5 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sliders/edit.html.erb
<h1>Editing slider</h1>

<%= render 'form' %>

<%= link_to 'Show', @slider %> |
<%= link_to 'Back', sliders_path %>

app/views/sliders/index.html.erb
<h1>Painel Principal</h1>

<table>
  <thead>
    <tr>
      <th>Description 1</th>
      <th>Description 2</th>
      <th>Description 3</th>
      <th>Description 4</th>
      <th>Description 5</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sliders.each do |slider| %>
      <tr>
        <td><%= slider.description_1 %></td>
        <td><%= slider.description_2 %></td>
        <td><%= slider.description_3 %></td>
        <td><%= slider.description_4 %></td>
        <td><%= slider.description_5 %></td>
        <td><%= link_to 'Show', slider %></td>
        <td><%= link_to 'Edit', edit_slider_path(slider) %></td>
        <td><%= link_to 'Destroy', slider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slider', new_slider_path %>

app/views/sliders/new.html.erb
<h1>New slider</h1>

<%= render 'form' %>

<%= link_to 'Back', sliders_path %>

app/views/sliders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description 1:</strong>
  <%= @slider.description_1 %>
</p>

<p>
  <strong>Description 2:</strong>
  <%= @slider.description_2 %>
</p>

<p>
  <strong>Description 3:</strong>
  <%= @slider.description_3 %>
</p>

<p>
  <strong>Description 4:</strong>
  <%= @slider.description_4 %>
</p>

<p>
  <strong>Description 5:</strong>
  <%= @slider.description_5 %>
</p>

<%= link_to 'Edit', edit_slider_path(@slider) %> |
<%= link_to 'Back', sliders_path %>