config/routes.rb
Rails.application.routes.draw do  get 'admin/index'
  resources 'sliders'
  resources 'services'
  resources 'structures'
  get 'inicio/index'
  root to: "inicio#index"
end

app/models/structure.rb
class Structure < ActiveRecord::Base
end

app/controllers/structures_controller.rb
class StructuresController < ApplicationController
  before_action :set_structure, only: [:show, :edit, :update, :destroy]

  # GET /structures
  # GET /structures.json
  def index
    @structures = Structure.all
  end

  # GET /structures/1
  # GET /structures/1.json
  def show
  end

  # GET /structures/new
  def new
    @structure = Structure.new
  end

  # GET /structures/1/edit
  def edit
  end

  # POST /structures
  # POST /structures.json
  def create
    @structure = Structure.new(structure_params)

    respond_to do |format|
      if @structure.save
        format.html { redirect_to @structure, notice: 'Structure was successfully created.' }
        format.json { render :show, status: :created, location: @structure }
      else
        format.html { render :new }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /structures/1
  # PATCH/PUT /structures/1.json
  def update
    respond_to do |format|
      if @structure.update(structure_params)
        format.html { redirect_to @structure, notice: 'Structure was successfully updated.' }
        format.json { render :show, status: :ok, location: @structure }
      else
        format.html { render :edit }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /structures/1
  # DELETE /structures/1.json
  def destroy
    @structure.destroy
    respond_to do |format|
      format.html { redirect_to structures_url, notice: 'Structure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_structure
      @structure = Structure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def structure_params
      params.require(:structure).permit(:left_title, :center_title, :center_description, :right_title)
    end
end

app/helpers/structures_helper.rb
module StructuresHelper
end

app/views/structures/_form.html.erb
<%= form_for(@structure) do |f| %>
  <% if @structure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@structure.errors.count, "error") %> prohibited this structure from being saved:</h2>

      <ul>
      <% @structure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :left_title %><br>
    <%= f.text_field :left_title %>
  </div>
  <div class="field">
    <%= f.label :center_title %><br>
    <%= f.text_field :center_title %>
  </div>
  <div class="field">
    <%= f.label :center_description %><br>
    <%= f.text_field :center_description %>
  </div>
  <div class="field">
    <%= f.label :right_title %><br>
    <%= f.text_field :right_title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/structures/edit.html.erb
<h1>Editing structure</h1>

<%= render 'form' %>

<%= link_to 'Show', @structure %> |
<%= link_to 'Back', structures_path %>

app/views/structures/index.html.erb
<h1>Listing structures</h1>

<table>
  <thead>
    <tr>
      <th>Left title</th>
      <th>Center title</th>
      <th>Center description</th>
      <th>Right title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @structures.each do |structure| %>
      <tr>
        <td><%= structure.left_title %></td>
        <td><%= structure.center_title %></td>
        <td><%= structure.center_description %></td>
        <td><%= structure.right_title %></td>
        <td><%= link_to 'Show', structure %></td>
        <td><%= link_to 'Edit', edit_structure_path(structure) %></td>
        <td><%= link_to 'Destroy', structure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Structure', new_structure_path %>

app/views/structures/new.html.erb
<h1>New structure</h1>

<%= render 'form' %>

<%= link_to 'Back', structures_path %>

app/views/structures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Left title:</strong>
  <%= @structure.left_title %>
</p>

<p>
  <strong>Center title:</strong>
  <%= @structure.center_title %>
</p>

<p>
  <strong>Center description:</strong>
  <%= @structure.center_description %>
</p>

<p>
  <strong>Right title:</strong>
  <%= @structure.right_title %>
</p>

<%= link_to 'Edit', edit_structure_path(@structure) %> |
<%= link_to 'Back', structures_path %>